name: Automated Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    if: github.event.pull_request.merged == true && (contains(github.event.pull_request.labels.*.name, 'major') || contains(github.event.pull_request.labels.*.name, 'minor') || contains(github.event.pull_request.labels.*.name, 'patch'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine next version
        id: semver
        run: |
          # Install semver tool
          npm install -g semver

          # Get latest tag or start with 0.0.0 if no tags exist
          git fetch --tags
          LATEST_TAG=$(git tag -l "v*" | sort -V | tail -n 1)
          if [ -z "$LATEST_TAG" ]; then
            LATEST_VERSION="0.0.0"
          else
            LATEST_VERSION=${LATEST_TAG#v}
          fi
          
          echo "Current version: $LATEST_VERSION"
          
          # Determine increment type based on PR label
          if [[ ${{ contains(github.event.pull_request.labels.*.name, 'major') }} == 'true' ]]; then
            NEXT_VERSION=$(semver -i major $LATEST_VERSION)
            RELEASE_TYPE="Major"
          elif [[ ${{ contains(github.event.pull_request.labels.*.name, 'minor') }} == 'true' ]]; then
            NEXT_VERSION=$(semver -i minor $LATEST_VERSION)
            RELEASE_TYPE="Minor"
          else
            NEXT_VERSION=$(semver -i patch $LATEST_VERSION)
            RELEASE_TYPE="Patch"
          fi
          
          echo "Next version: $NEXT_VERSION"
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV
          echo "RELEASE_TYPE=$RELEASE_TYPE" >> $GITHUB_ENV
          echo "version=v$NEXT_VERSION" >> $GITHUB_OUTPUT

      - name: Create Tag
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git tag -a v$NEXT_VERSION -m "$RELEASE_TYPE release: v$NEXT_VERSION"
          git push origin v$NEXT_VERSION

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            
            // Get PR details for release notes
            const prNumber = context.payload.pull_request.number;
            const prTitle = context.payload.pull_request.title;
            const prUrl = context.payload.pull_request.html_url;
            const version = process.env.NEXT_VERSION;
            
            // Create release notes with PR info
            const releaseNotes = `# v${version} (${new Date().toISOString().split('T')[0]})

            ## ${process.env.RELEASE_TYPE} Release

            This release was automatically generated from PR #${prNumber}: [${prTitle}](${prUrl})
            `;
            
            // Create or update the release
            github.rest.repos.createRelease({
              owner,
              repo,
              tag_name: `v${version}`,
              name: `v${version}`,
              body: releaseNotes,
              draft: false,
              prerelease: false
            });

